name: etu-smartchat

services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:1.0.11.dev29
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma-data:/chroma/chroma/
    ports:
      - 8000:8000
    networks:
      - net

  telegram-bot:
    build:
      context: .
      dockerfile: .Dockerfile
    volumes:
      - .:/app
      - ./models:/models
    working_dir: /app
    env_file:
      - ./src/.env
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  chroma-data:
    driver: local