name: etu-smartchat

services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:1.0.11.dev29
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma-data:/chroma/chroma/
    ports:
      - 8000:8000
    networks:
      - net

  telegram-bot:
    image: ghcr.io/abetlen/llama-cpp-python:v0.3.5
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - ./src/.env
    command: >
      bash -c "pip install --no-cache-dir -r ./src/requirements.txt && python ./src/app.py"
    networks:
      - net


networks:
  net:
    driver: bridge

volumes:
  chroma-data:
    driver: local