name: etu-smartchat

services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:1.0.11.dev29
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma-data:/chroma/chroma/
    ports:
      - 8000:8000
    networks:
      - net

#  telegram-bot:
#    image: python:3.11-slim
#    volumes:
#      - .:/app
#    working_dir: /app
#    env_file:
#      - .env
#    command: >
#      bash -c "pip install python-telegram-bot==22.1 && python ./serejs/telegram_bot.py"
#    networks:
#      - net


networks:
  net:
    driver: bridge

volumes:
  chroma-data:
    driver: local